### ISSUE TITLE
Feature request: Font size

### ISSUE THREAD

**Issue by VincentCATILLON** [henninghall/react-native-date-picker#109]
Hi,

Is it possible to add `textStyle` prop for the date picker ? to be able to have the same font size than my app :)

Thx for your work 🙏

**Comment by henninghall** [comment]
Hi, good idea, that would certainly be a good feature! 

The problem is that this is not possible to do on iOS since the UIDatePicker doesn't support it. On Android, I think it could be done. The only downside I see is that it would be an android specific feature. Still, I think it would be very appreciated! 

Do you think you would be able to make a PR with this feature? 🙂

**Comment by henninghall** [comment]
Changed my opinion about this, since Apple has chosen to limit the ability to change size (probably to prevent bad UX) I don't think we should do it on Android either. I also want to keep the features the same on both platforms.
