### ISSUE TITLE
Avoid using Moment

### ISSUE THREAD

**Issue by joelchelliah** [henninghall/react-native-date-picker#173]
This component is depending on the very large and complex **Moment** API,  to only do a few simple date computations in the file `DatePickerAndroid.js`.

Could you please consider removing **Moment** as a dependency, and use a more light-weight API (such as date-fns, or similar) to do those few lines of logic?

Thanks :)

**Comment by henninghall** [comment]
Sounds like a great idea! I will look into it. Or do you have time to make a PR yourself? :)

**Comment by stephanoparaskeva** [comment]
> Sounds like a great idea! I will look into it. Or do you have time to make a PR yourself? :)

Moment is almost 4mb and this package is already 135kb unpacked. It's a gamechanger so I'd definitely +1 this!

**Comment by henninghall** [comment]
@ stephanoparaskeva @joelchelliah 

I made some investigations and tried replacing moment with date-fns. I used the tool [react-native-bundle-visualizer](https://github.com/IjzerenHein/react-native-bundle-visualizer) on a fresh react-native app (installed react-native-date-picker installed on top) and got these result:

Moment 58KB 
Date-fns 152KB

The total bundle size diffs with around ~100KB as expected. Seems to me that moment is doing a pretty good job to only include necessary code, or am I missing something?

**Comment by stephanoparaskeva** [comment]
> @stephanoparaskeva @joelchelliah
> 
> I made some investigations and tried replacing moment with date-fns. I used the tool [react-native-bundle-visualizer](https://github.com/IjzerenHein/react-native-bundle-visualizer) on a fresh react-native app (installed react-native-date-picker installed on top) and got these result:
> 
> Moment 58KB
> Date-fns 152KB
> 
> The total bundle size diffs with around ~100KB as expected. Seems to me that moment is doing a pretty good job to only include necessary code, or am I missing something?

I think you might instead want to use Native JavaScript instead of any packages. I noticed that your repo only uses moment in less than 5 locations and managed to replace this all with native JavaScript. I can't make a PR because I ended up changing everything to react Hooks. But here is the repo and it shows that there is no external libraries needed whatsoever:
https://github.com/stephanoparaskeva/euclid-datepicker

Only posting this incase you wanted another way to reduce bundle size

**Comment by henninghall** [comment]
Thanks for the input. The reason for not using the javascript date object, and modifying it with setMinutes, is that I want to avoid problems around the daylight saving switch. [Longer explanation here](https://stackoverflow.com/questions/1197928/how-to-add-30-minutes-to-a-javascript-date-object/1214753#1214753).

**Comment by stephanoparaskeva** [comment]
> Thanks for the input. The reason for not using the javascript date object, and modifying it with setMinutes, is that I want to avoid problems around the daylight saving switch. [Longer explanation here](https://stackoverflow.com/questions/1197928/how-to-add-30-minutes-to-a-javascript-date-object/1214753#1214753).

Gotcha, that makes sense. Thanks for the explanation

**Comment by kentandersen** [comment]
Hate to digg up a closed isssue; but given that moment has declared itself [done](https://momentjs.com/docs/#/-project-status/), and is actively recommending other alternatives, I think it is time to revise the decision to include moment.js

Having wasted a good amount of time with daylight savings I understand you don't want to touch that with a 10ft pole. The longer explanation you are referring to discusses handling adding days by increasing the minutes by 24 * 60 * 60. This will have unfortunate consequences during daylight savings. However the usage of moment in this library is solely for parsing and serialising dates to iso timestamps with minute offset. In this case adding / subtracting minutes (in ms) to the date value will yield a correct result, especially since toISOString() returns timestamps in UTC (z) time.

I've also looking at the implementation of [setMinutes()](https://github.com/date-fns/date-fns/blob/master/src/addMilliseconds/index.js#L32) and [moment.add()](https://github.com/moment/moment/blob/develop/src/lib/moment/add-subtract.js#L52). They both use the same technique. Essentially they are just a wrappers around `new Date(date.valueOf() + minutes * 1000).`

After realising this, I believe it is safe to switch to a vanilla javascript version of add / subtract.
