### ISSUE TITLE
Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.

### ISSUE THREAD

**Issue by sudiddo** [henninghall/react-native-date-picker#25]
I followed the instruction, first i use yarn then react-native link

after that, this error happen
Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.

I try to remove your date picker and it's coming back to normal.

**Comment by henninghall** [comment]
Hi! Thanks for reporting this. Your issue is probably related to [this StackOverflow question] (https://stackoverflow.com/questions/37497882/errorexecution-failed-for-task-apptransformclasseswithdexfordebug-in-androi/37498040). You might have to enable multidex. 

Since this problem doesn't appear in the example project I doubt it has something to do with this package itself. Feel free to reopen the issue if I am wrong 🙂
