### ISSUE TITLE
Selecting Minimum Time

### ISSUE THREAD

**Issue by LightningNemesis** [henninghall/react-native-date-picker#311]
Is there a prop via which we can set a minimum time, just like we can set the minimum date? 
When we use the mode='datetime', setting the minimumDate stops the wheel at today (doesn't show anything earlier than today) but the time isn't restricted to the current time only.
Is there any way to implement this?

**Comment by henninghall** [comment]
Correct, the invalid dates are removed from the picker but the hours/minutes are still visible. 

This is not possible to change on iOS because of the limitations of UIDatePicker. On Android this would probably be possible, even though I am not fully aware of all implications. It is an interesting idea, feel free to try to implement it if you like and we can probably include it in the library.
