### ISSUE TITLE
Set default time

### ISSUE THREAD

**Issue by eviappstore** [henninghall/react-native-date-picker#315]
Is there any property to set the default time for the picker?

**Comment by henninghall** [comment]
The default value will be the value the `date` prop will has at initialization. For instance, use `new Date()` to use the current date.

**Comment by AlirezaHadjar** [comment]
Yeah, but this doesn't work with `mode="time"`.

**Comment by Marvedog** [comment]
I would request to re-open this @henninghall 

I think the issue here is the following.

### Create a `react-native-date-picker` with `minuteInterval={5}`

```js
<DatePicker
   date={new Date(2022, 1, 1, 1, 53)}
   locale="nb"
   minuteVariant={5}
   mode="time"
   onDateChange={(date) => console.log(date)}
  />
```

Then the `DatePicker` will default the time to "01:00" instead of "01:50" or "01:55" which would be the expected result depending on the configured `maxDate` or `minDate`

### Create a `react-native-date-picker` with `minuteInterval={1}`

```js
<DatePicker
   date={new Date(2022, 1, 1, 1, 53)}
   locale="nb"
   minuteVariant={1}
   mode="time"
   onDateChange={(date) => console.log(date)}
  />
```

The `DatePicker` will default to the expected time "01:53".
